-- MySQL Script generated by MySQL Workbench
-- Fri Apr  4 00:52:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema JuegoAhoracado
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `JuegoAhoracado` ;

-- -----------------------------------------------------
-- Schema JuegoAhoracado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JuegoAhoracado` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `JuegoAhoracado` ;

-- -----------------------------------------------------
-- Table `Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Administrador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Administrador` (
  `Usuario_idUsuario` INT NOT NULL,
  `nivel` ENUM("Nivel1", "Nivel2", "Nivel3") NOT NULL,
  `contraseña` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cuota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cuota` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cuota` (
  `idCuota` INT NOT NULL,
  `tipoCuota` ENUM("Premium", "Normal") NOT NULL,
  PRIMARY KEY (`idCuota`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Historico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Historico` (
  `idHistorico` INT NOT NULL,
  `nombrePalabraFrase` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idHistorico`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Idioma` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Idioma` (
  `idIdioma` INT NOT NULL,
  `nombreIdioma` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idIdioma`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Juego` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Juego` (
  `idJuego` INT NOT NULL,
  `fechaSystema` DATETIME NOT NULL,
  `horaSystema` TIME NOT NULL,
  PRIMARY KEY (`idJuego`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jugador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Jugador` (
  `Usuario_idUsuario` INT NOT NULL,
  `conttraseña` VARCHAR(12) NOT NULL,
  `Cuota_idCuota` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PalabrasFrases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PalabrasFrases` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PalabrasFrases` (
  `idPalabraFrase` INT NOT NULL,
  `nombrePalabraFrase` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idPalabraFrase`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Palabrasidiomas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Palabrasidiomas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Palabrasidiomas` (
  `idPalabraFrase` INT NOT NULL,
  `idIdioma` INT NOT NULL,
  PRIMARY KEY (`idPalabraFrase`, `idIdioma`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Partida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Partida` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Partida` (
  `idJuego` INT NOT NULL,
  `idJugador` INT NOT NULL,
  `idPalabraFrase` INT NOT NULL,
  `resultado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idJuego`, `idJugador`, `idPalabraFrase`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Sinonimos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sinonimos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Sinonimos` (
  `idPalabraFrase` INT NOT NULL,
  `idPalabraFraseSinonimo` INT NOT NULL,
  PRIMARY KEY (`idPalabraFrase`, `idPalabraFraseSinonimo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
